env:
  es2021: true
  node: true
extends:
  - airbnb-base
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 12
  sourceType: module
plugins:
  - '@typescript-eslint'
  - 'eslint-plugin-import'
rules: {
  "import/extensions": [
    "error",
    {
      "js": "never",
      "ts": "never",
    }
  ],
  "no-underscore-dangle": "off",
  "linebreak-style": "off",
}

settings:
  "import/resolver": {
    "node": {
      "extensions": [".js", ".ts"]
    }
  }
