@host = http://localhost:7000/shoppingcart

POST {{host}}/add
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token2}}

{
    "products": [{
        "id": "62010563d6443971bd88bfc9",
        "qty": 2,
        "priceId": "price_1KQVaxIRW0vBopkJkMeF95Jj"
    }]
}

###
GET {{host}}
Accept: application/json
Authorization: Bearer {{token2}}