@host = http://localhost:7000/menu

POST {{host}}/add
Content-Type: application/json
Accept: application/json


{
    "price": 15.00,
    "name": "Veggie 10 inch",
    "description": "Veggie 10 inch pizza"
}

###
GET {{host}}/all
Accept: application/json
Authorization: Bearer {{token}}