@host = http://localhost:7000/users

### Signup
POST {{host}}/signup
Accept: application/json
Content-Type: application/json

{
  "email": "alainchristian89@gmail.com",
  "password": "nAdia123",
  "streetAddress": "123 Main St",
  "name": "Alain Christian"
}

###
POST {{host}}/login
Accept: application/json
Content-Type: application/json

{
  "email": "alainchristian89@gmail.com",
  "password": "nAdia123"
}

###
DELETE {{host}}/logout/8c6d0cda-6020-40ab-862a-ed328d3fa8f1
Accept: application/json

####
GET {{host}}